@startuml
start
:Чтение файла;
if (Файл существует?) then (да)
  :Разбор;
  while (есть записи?) is (да)
    :Обработка записи;
  endwhile (нет)
else (нет)
  :Создать файл;
endif
:Запись результата;
stop
@enduml
